In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits = load_digits()

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [18]:
lr = LogisticRegression(max_iter=2000)
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9666666666666667

In [19]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9907407407407407

In [20]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.9685185185185186

In [21]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3, shuffle=True)


In [22]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print("Train:", train_index, "Test:", test_index)

Train: [0 4 5 6 7 8] Test: [1 2 3]
Train: [0 1 2 3 4 6] Test: [5 7 8]
Train: [1 2 3 5 7 8] Test: [0 4 6]


In [23]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [24]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [32]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kf.split(digits.data):
    X_train, X_test = digits.data[train_index], digits.data[test_index]
    y_train, y_test = digits.target[train_index], digits.target[test_index]

    scores_l.append(get_score(LogisticRegression(max_iter=1000), X_train, X_test, y_train, y_test))
    scores_svm.append(get_score(SVC(), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))


In [33]:
scores_l

[0.9549248747913188, 0.9732888146911519, 0.9599332220367279]

In [34]:
scores_svm

[0.989983305509182, 0.9766277128547579, 0.986644407345576]

In [35]:
scores_rf

[0.9782971619365609, 0.9699499165275459, 0.9699499165275459]

In [36]:
average_score_l = np.mean(scores_l)
average_score_svm = np.mean(scores_svm)
average_score_rf = np.mean(scores_rf)

In [37]:
average_score = np.mean([average_score_l, average_score_svm, average_score_rf])

In [38]:
average_score

np.float64(0.9732888146911519)

In [39]:
from sklearn.model_selection import cross_val_score

In [42]:
cross_val_score(LogisticRegression(max_iter=1000), digits.data, digits.target)

array([0.92222222, 0.87222222, 0.94150418, 0.94150418, 0.89693593])

In [43]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [53]:
cross_val_score(RandomForestClassifier(n_estimators=200), digits.data, digits.target)

array([0.93611111, 0.90555556, 0.96100279, 0.96100279, 0.92479109])